### ISSUE TITLE
请问有打算接入jaeger，或者zipkin么，谢谢，最近也要用go来重构项目。

### ISSUE THREAD

**Issue by penghcheng** [daodao97/egin#1]

**Comment by daodao97** [comment]
有计划接入 `jaeger`, 这个脚手架目前还在不断完善, 后续用于团队快速起业务, 有兴趣可以一起参与😁

**Comment by penghcheng** [comment]
okok



---原始邮件---
发件人: "刀刀"<notifications@github.com&gt;
发送时间: 2020年8月30日(周日) 晚上7:04
收件人: "daodao97/egin"<egin@noreply.github.com&gt;;
抄送: "penghcheng"<375488452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [daodao97/egin] 请问有打算接入jaeger，或者zipkin么，谢谢，最近也要用go来重构项目。 (#1)




 
有计划接入 jaeger, 这个脚手架目前还在不断完善, 后续用于团队快速起业务, 有兴趣可以一起参与😁
